version: 2.1

orbs:
  codacy: codacy/base@2.14.8
  slack: circleci/slack@3.3.0

references:
  restore_maven_dependencies: &restore_maven_dependencies
    restore_cache:
      keys:
        - maven-dependencies-1.0.13-{{ checksum "pom.xml" }}
        - maven-dependencies-1.0.13

  run_integration_tests: &run_integration_tests
    docker:
      - image: circleci/openjdk:8-jdk
    working_directory: ~/integration-tests
    steps:
      - run:
          name: Check if token exists
          command: |
            if [[ -z $SLACK_TOKEN ]]; then echo "Token is empty"; fi
      - run:
          name: Set right slack token
          command: |
            if [[ $ENVIRONMENT == "production" ]]
            then
              echo "export SLACK_TOKEN=$SLACK_TOKEN_PROD" >> $BASH_ENV
            else
              echo "export SLACK_TOKEN=$SLACK_TOKEN_STAGING" >> $BASH_ENV
            fi
      - slack/status:
          fail_only: false
          webhook: https://hooks.slack.com/services/$SLACK_TOKEN
          failure_message: ":red_circle: A $CIRCLE_JOB job has failed! See more on: $RP_LAUNCH_URL, login with the default user."

jobs:
  maven_dependencies:
    docker:
      - image: circleci/openjdk:8-jdk
        environment:
          JAVA_OPTS: "-XX:MinRAMPercentage=60.0 -XX:MaxRAMPercentage=90.0"
    environment:
      JAVA_OPTS: -Xmx3200m
    working_directory: ~/integration-tests
    steps:
      - add_ssh_keys:
          fingerprints:
            - "df:83:d7:c7:d5:79:06:c2:3b:d1:fd:e2:a3:d1:12:c5"
      - run:
          name: Checkout integration tests
          command: |
            ssh-keyscan bitbucket.org >> ~/.ssh/known_hosts
            bash -c "`curl -fsSL https://raw.githubusercontent.com/codacy/codacy-analysis-cli/master/scripts/checkout.sh`" -s git@bitbucket.org:qamine/qa-automation-tests.git ~/integration-tests master
      - *restore_maven_dependencies
      - run: mvn dependency:go-offline
      - run:
          name: Compile tests
          command: mvn test-compile
      - save_cache:
          key: maven-dependencies-1.0.13-{{ checksum "pom.xml" }}
          paths:
            - ~/.m2
  test_staging:
    <<: *run_integration_tests
    environment:
      TEST_PATH: Suite/CLI/STAGING.xml
      LAUNCH_TAG: CIRCLECI;CLI;STAGING
      PROJECT_NAME: codacy-analysis-cli
      LAUNCH_NAME: CLI_STAGING
      RP_LAUNCH_URL: https://reportportal.staging.codacy.org/ui/#codacy-analysis-cli/launches
      SLACK_TOKEN: $SLACK_TOKEN_STAGING
  test_production:
    <<: *run_integration_tests
    environment:
      TEST_PATH: Suite/CLI/PROD.xml
      CODACY_ANALYSIS_CLI_VERSION: latest
      LAUNCH_TAG: CIRCLECI;CLI;PROD
      PROJECT_NAME: codacy-analysis-cli
      LAUNCH_NAME: CLI_PROD
      RP_LAUNCH_URL: https://reportportal.staging.codacy.org/ui/#codacy-analysis-cli/launches
      SLACK_TOKEN: $SLACK_TOKEN_PROD

workflows:
  version: 2
  test-and-publish:
    jobs:
      - codacy/checkout_and_version:
          write_sbt_version: true
      - test_staging

  nightly:
    triggers:
      - schedule:
          cron: "0 0 * * *" # Every day “At minute 00:00”
          filters:
            branches:
              only:
                - master
    jobs:
      - maven_dependencies
      - test_production:
          requires:
            - maven_dependencies
